if [ -x /usr/bin/dircolors ]; then
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto';
fi

alias wget='wget --hsts-file=${XDG_DATA_HOME}/wget-hsts'

alias svn='svn --config-dir ${XDG_CONFIG_HOME}/subversion'

alias weather-util='weather-util --cachedir ${XDG_CACHE_HOME}/weather'

alias full-system-upgrade='sudo apt-get update; sudo apt-get -y dist-upgrade; sudo apt-get -y autoremove; sudo apt-get clean; sudo npm --global update; pipx upgrade-all; sudo snap refresh; flatpak update'

alias adb='HOME="${XDG_DATA_HOME}"/android adb'

alias dosbox='dosbox -conf "${XDG_CONFIG_HOME}/dosbox/dosbox.conf"'
