if [ -x /usr/bin/dircolors ]; then
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto';
fi

alias wget='wget --hsts-file=${XDG_DATA_HOME}/wget-hsts'

alias svn='svn --config-dir ${XDG_CONFIG_HOME}/subversion'

alias weather-util='weather-util --cachedir ${XDG_CACHE_HOME}/weather'
